version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - ENV=dev

  frontend:
    build: ./ai-ui
    ports:
      - "3000:3000"
    volumes:
      - ./ai-ui:/app
    environment:
      - ENV=dev
